# Generated by Django 5.2.1 on 2025-05-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tache',
            table='tache',
        ),
    ]
